[package]
name = "bairstow-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bairstow"
path = "src/lib.rs"

[dependencies]
threadpool = { version = "1.8.1" }
num = { version = "0.4.0" }
num-traits = { version = "0.2.14" }
approx_eq = { version = "0.1.8" }
# lds-rs = { path = "../lds-rs"}
